[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[dependencies]
maplit = "1.0.2"
cute = "0.3.0"
itertools = "0.10.5"

[dependencies.aoc]
path = "../.."

[features]
default = ["speedtest"]
speedtest = []